var DICTS = {
    "adjectieven": [
        { ru: "длинный", nl: "lang" },
        { ru: "короткий", nl: "kort" },
        { ru: "высокий", nl: "hoog" },
        { ru: "низкий", nl: "laag" },
        { ru: "толстый", nl: "vet" },
        { ru: "худой", nl: "slank" },
        { ru: "светлый", nl: "light" },
        { ru: "темный", nl: "donker" },
        { ru: "узкий", nl: "dun" },
        { ru: "широкий", nl: "dik" },
        { ru: "открытый", nl: "open" },
        { ru: "закрытый", nl: "dicht" },
        { ru: "кислый", nl: "zuur" },
        { ru: "сладкий", nl: "zoet" },
        { ru: "быстрый", nl: "snel" },
        { ru: "медленный", nl: "traag" },
        { ru: "сложный", nl: "moeilijk" },
        { ru: "простой", nl: "gemakkelijk" },
        { ru: "пустой", nl: "leeg" },
        { ru: "полный", nl: "vol" },
        { ru: "счастливый", nl: "gelukkig" },
        { ru: "грусный", nl: "verdrietig" },
        { ru: "холодный", nl: "koud" },
        { ru: "теплый", nl: "warm" },
        { ru: "красивый", nl: "mooi" },
        { ru: "уродливый", nl: "lelijk" },
        { ru: "короткий", nl: "kort" },
        { ru: "длинный", nl: "lang" },
        { ru: "голый", nl: "naakt" },
        { ru: "одетый", nl: "gekleed" },
        { ru: "прямой", nl: "stijl" },
        { ru: "вьющийся", nl: "gekruld" },
        { ru: "влажный", nl: "nat" },
        { ru: "сухой", nl: "droog" },
        { ru: "много", nl: "veel" },
        { ru: "мало", nl: "weinig" },
        { ru: "бедный", nl: "arm" },
        { ru: "богатый", nl: "rijk" },
        { ru: "тупой", nl: "versleten" },
        { ru: "острый", nl: "scherp" },
        { ru: "гладкий", nl: "glad" },
        { ru: "с колючками", nl: "met stekels" },
        { ru: "правый", nl: "rechter" },
        { ru: "левый", nl: "linker" },
        { ru: "съедобный", nl: "eetbaar" },
        { ru: "ядовитый", nl: "giftig" },
        { ru: "пугающий", nl: "gemeen" },
        { ru: "дружелюбный", nl: "lief" },
        { ru: "черно-белый", nl: "zwart-wit" },
        { ru: "цветной", nl: "gekleurd" },
        { ru: "нижний", nl: "onder" },
        { ru: "верхний", nl: "boven" },
        { ru: "хрупкий", nl: "zwak" }
    ],
    "voornaamwoorden": [
        { ru: "я", nl: "ik" },
        { ru: "ты", nl: "je,jij" },
        { ru: "Вы", nl: "u" },
        { ru: "он", nl: "he,hij" },
        { ru: "она", nl: "ze,zij" },
        { ru: "оно", nl: "het" },
        { ru: "мы", nl: "we,wij" },
        { ru: "вы", nl: "julie" },
        { ru: "они", nl: "ze,zij" },
        { ru: "мой", nl: "mijn" },
        { ru: "твой", nl: "jouw" },
        { ru: "Ваш", nl: "uw" },
        { ru: "его", nl: "zijn" },
        { ru: "её", nl: "haar" },
        { ru: "наш", nl: "ons,onze" },
        { ru: "ваш", nl: "julie" },
        { ru: "их", nl: "hun" }
    ],
    "getallen": [
        { ru: "0", nl: "nul" },
        { ru: "1", nl: "één" },
        { ru: "2", nl: "twee" },
        { ru: "3", nl: "drie" },
        { ru: "4", nl: "vier" },
        { ru: "5", nl: "vijf" },
        { ru: "6", nl: "zes" },
        { ru: "7", nl: "zeven" },
        { ru: "8", nl: "acht" },
        { ru: "9", nl: "negen" },
        { ru: "10", nl: "tien" },
        { ru: "11", nl: "elf" },
        { ru: "12", nl: "twaalf" },
        { ru: "13", nl: "dertien" },
        { ru: "20", nl: "twintig" },
        { ru: "30", nl: "dertig" },
        { ru: "80", nl: "tachtig" },
        { ru: "100", nl: "honderd" },
        { ru: "1000", nl: "duizend" }
    ],
    "werkwoorden-1": [
        { ru: "идти", nl: "gaan" },
        { ru: "иметь", nl: "hebben" },
        { ru: "быть", nl: "zijn" },
        { ru: "смотреть", nl: "kijken" },
        { ru: "слушать", nl: "luisteren" },
        { ru: "играть", nl: "spelen" },
        { ru: "работать", nl: "werken" },
        { ru: "петь", nl: "zingen" },
        { ru: "слышать", nl: "horen" },
        { ru: "стирать", nl: "was doen" },
        { ru: "пылесосить", nl: "stofzuigen" },
        { ru: "покупать еду", nl: "boodshapen doen" },
        { ru: "ходить по магазинам", nl: "winkelen" },
        { ru: "выносить мусор", nl: "vuilniszakken buiten zetten" },
        { ru: "готовить", nl: "koken" },
        { ru: "убираться", nl: "poetsen" },
        { ru: "гладить", nl: "strijken" },
        { ru: "гулять", nl: "wandelen" },
        { ru: "идти дождь", nl: "regennen" },
        { ru: "находить", nl: "vinden" },
        { ru: "ставить", nl: "zetten" },
        { ru: "говорить", nl: "zeggen" },
        { ru: "сидеть", nl: "zitten" },
        { ru: "видеть", nl: "zien" },
        { ru: "есть", nl: "eten" },
        { ru: "говорить на языке", nl: "spreken" },
        { ru: "обедать", nl: "lunchen" },
        { ru: "жить", nl: "wonen" },
        { ru: "побеждать", nl: "winnen" },
    ],
    "werkwoorden-2": [
        { ru: "отправляться", nl: "vertrekken" },
        { ru: "брать", nl: "nemen" },
        { ru: "покупать", nl: "kopen" },
        { ru: "спрашивать", nl: "vragen" },
        { ru: "отвечать", nl: "antwoorden" },
        { ru: "стоять", nl: "staan" },
        { ru: "вставать", nl: "opstaan" },
        { ru: "оставаться", nl: "blijven" },
        { ru: "приносить, носить", nl: "brengen" },
        { ru: "мочь", nl: "kunnen" },
        { ru: "завтракать", nl: "ontbijten" },
        { ru: "бегать, ходить пешком", nl: "lopen" },
        { ru: "есть конфетки", nl: "snoepen" },
        { ru: "спать", nl: "slapen" },
        { ru: "навещать", nl: "bezoeken" },
        { ru: "носить одежду", nl: "dragen" },
        { ru: "жаловаться", nl: "klagen" },
        { ru: "писать по буквам", nl: "spellen" },
        { ru: "отдыхать", nl: "rusten" },
        { ru: "жениться", nl: "trouwen" }
    ],
    "housing": [
        { nl: "bezichtiging", ru: "просмотр" },
        { nl: "makelaar", ru: "маклер" },
        { nl: "overleg", ru: "переговоры" },
        { nl: "eigenaar", ru: "владелец" },
        { nl: "overigens", ru: "кроме того" },
        { nl: "onhandig", ru: "неудобно" },
        { nl: "qua", ru: "с точки зрения" },
        { nl: "verbinding", ru: "соединение" },
        { nl: "meerdere", ru: "несколько" },
        { nl: "klaar", ru: "готовый" },
        { nl: "ambassade", ru: "посольство" },
        { nl: "volgende", ru: "следующий" },
        { nl: "helaas", ru: "к несчастью" },
        { nl: "exacte", ru: "точный" },
        { nl: "later", ru: "позже" },
        { nl: "alleen", ru: "только" },
        { nl: "beschikbaar", ru: "доступный" },
        { nl: "afgelopen", ru: "прошедший" },
        { nl: "aantal", ru: "некоторое кол-во" },
        { nl: "voorstel", ru: "предложение" },
        { nl: "toerist", ru: "турист" },
        { nl: "beschadigen", ru: "повреждать" },
        { nl: "vooral", ru: "в основном" },
        { nl: "weer", ru: "снова" },
        { nl: "woonhuizen", ru: "жилые дома" },
        { nl: "waardevol", ru: "ценный" },
        { nl: "omgeving", ru: "окрестности" },
        { nl: "beslissing", ru: "решение" },
        { nl: "belangrijk", ru: "важный" },
        { nl: "ervaring", ru: "опыт" },
        { nl: "in verband met", ru: "в связи с" },
        { nl: "eenkomst", ru: "договор" },
        { nl: "huurovereenkomst", ru: "договор аренды" },
        { nl: "deel", ru: "часть" },
        { nl: "nogmaals", ru: "снова" },
        { nl: "geslaagd", ru: "успешный" },
        { nl: "prachtig", ru: "великолепный" },
        { nl: "indien akkoord", ru: "если согласны" },
    ],
    "3 Jan": [
        { ru: "лемон", nl: "citroen" },
        { ru: "улица", nl: "straat" },
        { ru: "строить", nl: "gebouwen" },
        { ru: "здание", nl: "gebouw" },
        { ru: "автострада", nl: "snelweg" },
        { ru: "дорога", nl: "weg" },
        { ru: "отмечать ДР", nl: "verjaaren" },
        { ru: "день рождения", nl: "verjaardag" },
        { ru: "рождаться", nl: "geboren" },
        { ru: "дата рождения", nl: "geboortedatum" },
        { ru: "поздравлять", nl: "feliciteren" },
        { ru: "поздравляю", nl: "feliciteerd, proficiat" },
        { ru: "именинник", nl: "jarig" },
        { ru: "пасха", nl: "pasen" },
        { ru: "пн. после пасхи", nl: "pasensmaandag" },
        { ru: "календарь", nl: "kalender" },
        { ru: "дата", nl: "datum, data" },
        { ru: "открытка", nl: "kaartje" },
        { ru: "весна", nl: "lente, voorjaar" },
        { ru: "осень", nl: "herfst, najaar" },
        { ru: "лето", nl: "zomer" },
        { ru: "зима", nl: "winter" },
        { ru: "январь", nl: "januari" },
        { ru: "февраль", nl: "februari" },
        { ru: "март", nl: "maart" },
        { ru: "апрель", nl: "april" },
        { ru: "май", nl: "mei" },
        { ru: "июнь", nl: "juni" },
        { ru: "июль", nl: "juli" },
        { ru: "август", nl: "augustus" },
        { ru: "сентябрь", nl: "september" },
        { ru: "октябрь", nl: "oktober" },
        { ru: "ноябрь", nl: "november" },
        { ru: "декабрь", nl: "december" },
        { ru: "подарак", nl: "geschenk,cadeau" }
    ],
    "5 Jan": [
        { ru: "помидор", nl: "tomaat" },
        { ru: "учительница", nl: "lerares" },
        { ru: "учитель", nl: "leraar" },
        { ru: "улыбаться", nl: "glimlachen" },
        { ru: "использовать", nl: "gebruiken, verbruiken" },
        { ru: "причесывать", nl: "kammen" },
        { ru: "причесываться", nl: "zich kammen" },
        { ru: "это возможно", nl: "dat kan" },
        { ru: "это не возможно", nl: "dat kan niet" },
        { ru: "решение", nl: "oplossing" },
        { ru: "все ещё", nl: "nog" },
        { ru: "уже", nl: "al" },
        { ru: "еще не", nl: "nog geen/niet" },
        { ru: "больше не", nl: "geen/niet meer" },
        { ru: "где-либо", nl: "ergens" },
        { ru: "повсюду", nl: "overal" },
        { ru: "нигде", nl: "nergens" },
        { ru: "когда-либо", nl: "ooit" },
        { ru: "иногда", nl: "soms" },
        { ru: "всегда", nl: "altijd" },
        { ru: "никогда", nl: "nooit" },
        { ru: "что-либо", nl: "iets" },
        { ru: "все", nl: "alles" },
        { ru: "ничего", nl: "niets" },
        { ru: "кто-либо", nl: "iemand" },
        { ru: "никто", nl: "niemand" },
        { ru: "звонить", nl: "bellen" },
        { ru: "сильное отрицание", nl: "sterke negatie" },
        { ru: "полностью", nl: "helemaal" },
        { ru: "действительно", nl: "echt" },
        { ru: "абсолютно", nl: "absoluut" },
        { ru: "кончено", nl: "zeker" },
        { ru: "сверху", nl: "boven" },
        { ru: "снизу", nl: "beneden" },
        { ru: "нужно", nl: "heb ... nodig" },
        { ru: "прекрасный", nl: "heerlijk" },
        { ru: "снизу", nl: "beneden" }
    ],
    "10 Jan": [
        { ru: "записываться на прием", nl: "afspraak maken" },
        { ru: "парикмахер", nl: "kapper" },
        { ru: "терапевт", nl: "huisarts" },
        { ru: "стоматолог", nl: "tandarts" },
        { ru: "я хотел бы", nl: "ik wil graag" },
        { ru: "мыть", nl: "wassen" },
        { ru: "стричь", nl: "knippen" },
        { ru: "если можно", nl: "als het kan" },
        { ru: "место", nl: "plek" },
        { ru: "благодарить", nl: "bedanken" },
        { ru: "жалоба", nl: "klacht" },
        { ru: "поясница", nl: "onderrug" },
        { ru: "подойти", nl: "langskomen" },
        { ru: "возможный", nl: "mogelijk" },
        { ru: "возможность", nl: "mogelijkheid" },
        { ru: "резать", nl: "snijden" },
        { ru: "надевать", nl: "aankleden" },
        { ru: "чистить зубы", nl: "tanden poetsen" },
        { ru: "мыть голову", nl: "haar wassen" },
        { ru: "печатать", nl: "typen" },
        { ru: "подметать", nl: "vegen" },
        { ru: "расслабляться", nl: "ontspannen", d: 1 },
        { ru: "давать постричь волосы", nl: "haar laten knippen" },
        { ru: "просыпаться", nl: "wakker worden" },
        { ru: "кормить", nl: "voeden" },
        { ru: "курить", nl: "roken" },
        { ru: "поливать", nl: "water geven" },
        { ru: "брить", nl: "scheren" },
        { ru: "принимать ванную", nl: "een bad nemen" },
        { ru: "принимать душ", nl: "een douche nemen" }
    ],
    "12 Jan": [
        { ru: "повторять", nl: "herhalen" },
        { ru: "подходить", nl: "passen" },
        { ru: "заполнять", nl: "invullen" },
        { ru: "данные", nl: "gegevens" },
        { ru: "формальный", nl: "formeel" },
        { ru: "разговор", nl: "gesprek" },
        { ru: "проводить", nl: "voeren", d: 1 },
        { ru: "фамилия", nl: "naam, achternaam" },
        { ru: "имя", nl: "voornaam" },
        { ru: "почтовый ящик", nl: "bus, brievenbus" },
        { ru: "район", nl: "gemeente", d: 1 },
        { ru: "этаж", nl: "verdieping" },
        { ru: "запрашивать", nl: "aanvragen" },
        { ru: "для того чтобы", nl: "om" },
        { ru: "бесплатно", nl: "gratis", d: 1 },
        { ru: "получать, принимать", nl: "ontvangen", d: 2},
        { ru: "частица -ка", nl: "even" },
        { ru: "обратно", nl: "terug" },
        { ru: "далее, вперед", nl: "verder" },
        { ru: "отправлять", nl: "sturen" },
        { ru: "посылка", nl: "verzending" },
        { ru: "популярный", nl: "populair" },
        { ru: "согласно", nl: "volgens" },
        { ru: "забывать", nl: "vergeten" },
        { ru: "постоянно", nl: "steeds", d: 2 },
        { ru: "ждать", nl: "wachten" },
        { ru: "выходить развлечся", nl: "uitgaan" }
    ],
    "14 Jan": [
        { ru: "встречаться", nl: "afspreken, ontmoeten" },
        { ru: "следовать", nl: "volgen" },
        { ru: "деревня", nl: "dorp" },
        { ru: "журнал", nl: "krant" },
        { ru: "иностранец", nl: "buitenlander" },
        { ru: "потому что", nl: "want, omdat" },
        { ru: "тарелка", nl: "bort" },
        { ru: "раньше", nl: "vroeger" },
        { ru: "довольный", nl: "blij" },
        { ru: "забастовка", nl: "staking" },
        { ru: "злой", nl: "boos" },
        { ru: "начальник", nl: "baas" },
        { ru: "овощ", nl: "groente" },
        { ru: "овощи", nl: "groenten" },
        { ru: "фрукты", nl: "fruit" },
        { ru: "уставший", nl: "moe" },
        { ru: "почему", nl: "waarom" },
        { ru: "хороший", nl: "fijn" }
    ],
    "17 Jan": [
        { ru: "градусы", nl: "graden" },
        { ru: "светить", nl: "schijnen" },
        { ru: "переменная облачность", nl: "halfbewolken" },
        { ru: "тучи (глагол)", nl: "bewolken" },
        { ru: "туча", nl: "wolk" },
        { ru: "снег", nl: "sneeuw" },
        { ru: "дождь с грозой", nl: "onweer" },
        { ru: "ветер", nl: "wind" },
        { ru: "дуть", nl: "waaien" },
        { ru: "надувать", nl: "blazen" },
        { ru: "туман", nl: "mist" },
        { ru: "град", nl: "hagel" },
        { ru: "град (глагол)", nl: "hagelen" },
        { ru: "радуга", nl: "regenboog" },
        { ru: "молния", nl: "bliksem" },
        { ru: "гром", nl: "donder" },
        { ru: "гром (глагол)", nl: "donderren" },
        { ru: "пляж", nl: "strand" },
        { ru: "солнечно", nl: "zonnig" },
        { ru: "туманно", nl: "mistig" },
        { ru: "погода", nl: "het weer" },
        { ru: "полностью", nl: "volledig" },
        { ru: "желать что-то", nl: "zin hebben van iets" },
        { ru: "занятый", nl: "bezig" },
        { ru: "отсутствующий", nl: "afwezig" },
        { ru: "редко", nl: "heel soms" },
        { ru: "иногда", nl: "soms, af en toe" },
        { ru: "почти", nl: "bijna" },
        { ru: "круассан", nl: "koffiekoekje" },
        { ru: "многократно", nl: "meerdere keren" },
        { ru: "единица чего-либо", nl: "stuk" },
        { ru: "в большинстве случаев", nl: "meestal" },
        { ru: "тяжелый", nl: "zwaar" },
        { ru: "мягкий", nl: "zacht" },
        { ru: "твердый", nl: "hard" }
    ],
    "19 Jan": [
        { ru: "вещь", nl: "ding" },
        { ru: "лестница", nl: "trap" },
        { ru: "комната", nl: "kamer" },
        { ru: "проход", nl: "gang" },
        { ru: "снаружи", nl: "buiten" },
        { ru: "внутри", nl: "binnen" },
        { ru: "река", nl: "rivier" },
        { ru: "лес", nl: "het bos" },
        { ru: "сад", nl: "tuin" },
        { ru: "летать", nl: "vliegen" },
        { ru: "стена", nl: "muur" },
        { ru: "мышь", nl: "muis" },
        { ru: "прыгать", nl: "springen" },
        { ru: "коробка", nl: "doos" },
        { ru: "кролик", nl: "konijn" },
        { ru: "мост", nl: "brug" },
        { ru: "далеко от", nl: "ver van" },
        { ru: "недалеко от", nl: "dicht van" },
        { ru: "далекий", nl: "ver" },
        { ru: "с ... до ...", nl: "van ... tot ..." },
        { ru: "из ... в ...", nl: "van ... naar ..." },
        { ru: "около, рядом", nl: "bij, naast" },
        { ru: "под", nl: "onder" },
        { ru: "за, о", nl: "aan" },
        { ru: "до, перед, для", nl: "voor" },
        { ru: "после", nl: "na" },
        { ru: "из", nl: "uit" },
        { ru: "вокруг", nl: "rond" },
        { ru: "вдоль", nl: "langs" },
        { ru: "позади", nl: "achter" },
        { ru: "сквозь", nl: "door" },
        { ru: "над", nl: "boven, over" },
        { ru: "вдоль и оперевшись", nl: "tegen" },
        { ru: "между", nl: "tussen" },
        { ru: "напротив", nl: "tegenover" },
        { ru: "направление движения", nl: "naar" },
        { ru: "в (место)", nl: "in" },
        { ru: "в (день недели), на, по", nl: "op" },
        { ru: "вешалка для одежды", nl: "kapstok" },
        { ru: "вдова", nl: "weduwe" },
        { ru: "общественный", nl: "openbaar" },
        { ru: "транспорт", nl: "vervoer" },
        { ru: "сломанный", nl: "kapot" },
        { ru: "ломать", nl: "kapot maken" },
        { ru: "уведомлять", nl: "verwittigen" }
    ],
    "21 Jan": [
        { ru: "лоб", nl: "voorhoofd" },
        { ru: "ухо", nl: "oor" },
        { ru: "нос", nl: "neus" },
        { ru: "ноздря", nl: "neusgat" },
        { ru: "усы", nl: "snor" },
        { ru: "бровь", nl: "wenkbrauw" },
        { ru: "подбородок", nl: "kin" },
        { ru: "губа", nl: "lip" },
        { ru: "губы", nl: "lippen" },
        { ru: "рот", nl: "mond" },
        { ru: "глаз", nl: "oog" },
        { ru: "язык", nl: "tong" },
        { ru: "щека", nl: "wang" },
        { ru: "ресницы", nl: "wimpers" },
        { ru: "борода", nl: "baard" },
        { ru: "лицо", nl: "gezicht" },
        { ru: "морщины", nl: "rimpels" },
        { ru: "челюсть", nl: "kaak" },
        { ru: "веснушки", nl: "sproeten" },
        { ru: "пятка", nl: "hiel" },
        { ru: "примерно", nl: "ongeveer" },
        { ru: "ключ", nl: "sleutel" },
        { ru: "шкаф", nl: "kast" },
        { ru: "доска", nl: "het bord" },
        { ru: "вместе", nl: "mee" },
        { ru: "в офисе", nl: "op kantoor" },
        { ru: "забор", nl: "hek" },
        { ru: "хижина", nl: "hut" },
        { ru: "крыша", nl: "het dak" },
        { ru: "замок", nl: "het slot" },
        { ru: "вход", nl: "ingang" },
        { ru: "порог", nl: "drempel" },
        { ru: "окно", nl: "het raam" },
        { ru: "прихожая", nl: "gang" },
        { ru: "коридор", nl: "hal" },
        { ru: "половик", nl: "mat" },
        { ru: "гостиная", nl: "woonkamer" },
        { ru: "мебель", nl: "meubels" },
        { ru: "ваза", nl: "vaas" },
        { ru: "скамейка, кушетка", nl: "bank" },
        { ru: "отопление", nl: "verwarming" },
        { ru: "кран", nl: "kraan" },
        { ru: "кухонная поверхность", nl: "het aanrecht" },
        { ru: "лестница", nl: "trap" },
        { ru: "полотенце", nl: "handdoek" },
        { ru: "зеркало", nl: "spiegel" },
        { ru: "шторы", nl: "het gordijn" },
        { ru: "подушка", nl: "het kussen" },
        { ru: "одеяло", nl: "deken" },
        { ru: "план помещения", nl: "la" },
        { ru: "чердак", nl: "zolder" },
        { ru: "кладовка", nl: "kelder" },
        { ru: "стена", nl: "wand" },
        { ru: "пол", nl: "vloer" },
        { ru: "люстра", nl: "het plafond" },
        { ru: "содержание дома", nl: "het huishouden" },
        { ru: "домохозяйка", nl: "huisvrouw" },
        { ru: "пыль", nl: "het stof" },
        { ru: "ведро", nl: "emmer" },
        { ru: "позвонить", nl: "aanbellen" },
        { ru: "удобный", nl: "handig" },
        { ru: "простой", nl: "eenvoudig" },
        { ru: "милый", nl: "gezellig" },
        { ru: "возможно", nl: "misschien" },
        { ru: "шум", nl: "lawaai" },
        { ru: "тишина", nl: "stilte" },
        { ru: "тихий", nl: "stil" },
        { ru: "громкий", nl: "luid" }
    ],
    "24 Jan": [
        { ru: "небо", nl: "hemel" },
        { ru: "переезд", nl: "verhuizing" },
        { ru: "лежать", nl: "liggen" },
        { ru: "класть", nl: "leggen" },
        { nl: "heel", ru: "целый, полный" },
        { nl: "inademen", ru: "вдыхать" },
        { nl: "uitademen", ru: "выдыхать" },
        { nl: "aanvaarden", ru: "оценивать" },
        { nl: "aanschouwen", ru: "предусматривать" },
        { nl: "aanbidden", ru: "предлагать" },
        { nl: "voorspellen", ru: "предсказывать" },
        { nl: "weerman", ru: "синоптик" },
        { nl: "doorzien", ru: "просматривать" },
        { nl: "omhelzen", ru: "обнимать" },
        { nl: "oversteken", ru: "переходить (дорогу)" },
        { nl: "overschatten", ru: "переоценивать" },
        { nl: "ondertekenen", ru: "подписывать" },
        { nl: "onderschatten", ru: "недооценивать" },
        { nl: "gebeuren", ru: "случаться, происходить" },
        { nl: "binnenkomen", ru: "входить внутрь" },
        { nl: "buitengaan", ru: "выходить" },
        { nl: "thuisblijven", ru: "оставаться дома" },
        { nl: "afdrogen", ru: "сушить" },
        { nl: "hoek", ru: "угол" },
        { nl: "recht", ru: "прямо" }
    ],
    "26 Jan": [
        { nl: "paken", ru: "схватить" },
        { nl: "trouwens", ru: "кстати" },
        { nl: "langzaam", ru: "медленный" },
        { nl: "druk", ru: "занятый (не о человеке)" },
        { nl: "transport middelen", ru: "транспортные средства" },
        { nl: "praten", ru: "болтать" },
        { nl: "afstand", ru: "расстояние" },
        { nl: "beweging", ru: "движение" },
        { nl: "toch", ru: "несмотря на, тем не менее" },
        { nl: "dus", ru: "то есть, таким образом" },
        { nl: "verliezen", ru: "терять" },
        { nl: "last hebben van iets", ru: "страдать от чего-либо" },
        { nl: "kleren", ru: "одежда" },
        { nl: "ruim", ru: "просторный" },
        { nl: "breed", ru: "широкий" },
        { nl: "hangen", ru: "висеть" },
        { nl: "spoor", ru: "путь" },
        { nl: "dat past", ru: "держите без сдачи" },
        { nl: "enkel ticket", ru: "билет в один конец" },
        { nl: "heen en terug", ru: "туда и обратно" },
        { nl: "doel", ru: "цель" }
    ],
    "28 Jan": [
        { nl: "luchtballon", ru: "воздушный шар" },
        { nl: "brandweerwagen", ru: "пожарная машина" },
        { nl: "dubbeldekbus", ru: "двухэтажный автобус" },
        { nl: "schoolbus", ru: "школьный автобус" },
        { nl: "bestelwagen", ru: "машина доставки" },
        { nl: "tractor", ru: "трактор" },
        { nl: "trekker", ru: "тягач" },
        { nl: "vuilniswagen", ru: "мусоровоз" },
        { nl: "aanhangwagen", ru: "прицеп" },
        { nl: "hoogtewerker", ru: "машина-подъемник" },
        { nl: "vrachtwagen", ru: "грузовик" },
        { nl: "ambulance, ziekenwagen", ru: "машина скорой помощи" },
        { nl: "politieauto", ru: "полицейская машина" },
        { nl: "helikopter", ru: "вертолет" },
        { nl: "refueler", ru: "бензовоз" },
        { nl: "lagere school", ru: "начальная школа" },
        { nl: "met vriendelijke groeten", ru: "c наилучшими пожеланиями" },
        { nl: "alvast bedankt", ru: "заранее благодарю" },
        { nl: "houden", ru: "любить, держать" },
        { nl: "stipt", ru: "пунктуальный" },
        { nl: "noteren", ru: "отмечать" },
        { nl: "aanwezig", ru: "присутствующий" },
        { nl: "zo snel/spoedig mogelijk", ru: "как можно быстрее (asap)" },
        { nl: "bespreken", ru: "обсуждать" },
        { nl: "oudercontact", ru: "родительское собрание" },
        { nl: "daarom", ru: "поэтому, следовательно" },
        { nl: "niet meer veraf", ru: "уже не далеко" },
        { nl: "beste, geachte", ru: "уважаемый" },
        { nl: "uitnodigen", ru: "приглашать" },
        { nl: "uitnodiging", ru: "приглашение" },
        { nl: "drukken", ru: "нажимать" },
        { nl: "kiezen", ru: "выбирать" },
        { nl: "alcoholische", ru: "алкогольный" },
        { nl: "frisdrank", ru: "безалкогольный" },
        { nl: "steken", ru: "вставлять" },
        { nl: "aan beweging doen", ru: "объезжать" },
        { nl: "hoeven", ru: "должен" }
    ],
    "31 Jan": [
        { nl: "voor maaltijd", ru: "до еды" },
        { nl: "tijdens maaltijd", ru: "во время еды" },
        { nl: "na maaltijd", ru: "после еды" },
        { nl: "neusspray", ru: "спрей для носа" },
        { nl: "zuigtabletten", ru: "таблетки для рассасывания" },
        { nl: "bronсhitis", ru: "бронхит" },
        { nl: "innemen", ru: "принимать" },
        { nl: "keelontsteking", ru: "ларингит" },
        { nl: "griep", ru: "грипп" },
        { nl: "verkouden", ru: "простуженный" },
        { nl: "niesen", ru: "чихать" },
        { nl: "koorts", ru: "лихорадка" },
        { nl: "hoesten", ru: "кашлять" },
        { nl: "keelpijn", ru: "боль в горле" },
        { nl: "hoofdpijn", ru: "головная боль" },
        { nl: "rugpijn", ru: "боль в спине" },
        { nl: "tandpijn", ru: "зубная боль" },
        { nl: "oorpijn", ru: "боль в ухе" },
        { nl: "oogpijn", ru: "боль в глазу" },
        { nl: "buikpijn", ru: "боль в животе" },
        { nl: "vingerpijn", ru: "боль в пальце" },
        { nl: "neuspijn", ru: "боль в носу" },
        { nl: "pijn aan arm", ru: "боль в руке" },
        { nl: "pijn aan hand", ru: "боль в кисте" },
        { nl: "pijn aan hiel", ru: "боль в пятке" },
        { nl: "pijn aan been", ru: "боль в ноге" },
        { nl: "pijn aan knie", ru: "боль в колене" },
        { nl: "pijn aan teen", ru: "боль в пальце на ноге" },
        { nl: "enkel na afspraak", ru: "только по предварительной записи" },
        { nl: "spreekuuh", ru: "часы приема" },
        { nl: "ziekenfonds", ru: "фонд медицинского страхования" },
        { nl: "ziektebrief", ru: "больничный лист" },
        { nl: "waar doet pijner?", ru: "где болит?" },
        { nl: "Wat scheelt er? / Wat gebeurt?", ru: "что случилось?" },
        { nl: "zich voelen", ru: "чувствовать себя" },
        { nl: "rode bes", ru: "красная смородина" },
        { nl: "pruim", ru: "слива" },
        { nl: "perzik", ru: "персик" },
        { nl: "peer", ru: "груша" },
        { nl: "mandarijn", ru: "мандарин" },
        { nl: "lychee", ru: "личи" },
        { nl: "kiwi", ru: "киви" },
        { nl: "grapefruit", ru: "грепфрут" },
        { nl: "granaatappel", ru: "гранат" },
        { nl: "framboos", ru: "малина" },
        { nl: "dadel", ru: "финики" },
        { nl: "appel", ru: "яблоко" },
        { nl: "abrikoos", ru: "абрикос" },
        { nl: "aardbei", ru: "клубника" },
        { nl: "witlof", ru: "цикорий" },
        { nl: "winterpostelein", ru: "зимний портулак" },
        { nl: "spruiten", ru: "брюссельская капуста" },
        { nl: "spinazie", ru: "шпинат" },
        { nl: "rucola", ru: "рукола" },
        { nl: "rode kool", ru: "красная капуста" },
        { nl: "rode biet", ru: "свекла" },
        { nl: "pastinaak", ru: "пастернак" },
        { nl: "kropsla", ru: "пучек салата" },
        { nl: "koolraap", ru: "кольраби" },
        { nl: "boerenkool", ru: "кале" },
        { nl: "bloemkool", ru: "цветная капуста" },
        { nl: "selderij", ru: "сельдерей" },
        { nl: "aubergine", ru: "баклажан" },
        { nl: "andijvie", ru: "эндивий" },
        { nl: "daarom, daarop", ru: "поэтому" }
    ],
    "2 Feb": [
        { nl: "wereldbol", ru: "глобус" },
        { nl: "kwast", ru: "кисточка" },
        { nl: "lijm", ru: "клей" },
        { nl: "juf", ru: "классный руководитель" },
        { nl: "tekenen", ru: "рисовать" },
        { nl: "liniaal", ru: "линейка" },
        { nl: "het potlood", ru: "карандаш" },
        { nl: "rij", ru: "очередь" },
        { nl: "puntenslijper", ru: "точилка" },
        { nl: "slijpen", ru: "точить" },
        { nl: "zand", ru: "песок" },
        { nl: "zandbak", ru: "песочница" },
        { nl: "schaar", ru: "ножницы" },
        { nl: "stift, marker", ru: "маркер" },
        { nl: "tekening", ru: "рисунок" },
        { nl: "krijtje", ru: "мел" },
        { nl: "meester", ru: "завуч" },
        { nl: "rekenen", ru: "считать" },
        { nl: "het plakband", ru: "скотч" },
        { nl: "dop", ru: "крышка" },
        { nl: "hoe dikwijls", ru: "как часто" },
        { nl: "stoot", ru: "шишка" },
        { nl: "contra indicaties", ru: "противопоказания" },
        { nl: "betallen", ru: "платить" },
        { nl: "dokter van wacht", ru: "дежурный доктор" },
        { nl: "apotheek van wacht", ru: "дежурная аптека" },
        { nl: "salaris", ru: "зарплата" },
        { nl: "stijgen", ru: "повышать" },
        { nl: "verkoudheid", ru: "простуда" },
        { nl: "genezen", ru: "лечить" },
        { nl: "volledig tijd werk", ru: "полный рабочий день" },
        { nl: "gedeeltelijk tijd werk", ru: "неполный рабочий день" },
        { nl: "verboden", ru: "запрещенный" },
        { nl: "toegelaten", ru: "разрешеный" },
        { nl: "ongeval", ru: "дорожное происшествие" },
        { nl: "ziekte", ru: "болезнь" },
        { nl: "om reden van", ru: "по причине" },
        { nl: "ongeschiktheidsattest", ru: "листок нетрудоспособности" },
        { nl: "apotheker", ru: "фармацевт" },
        { nl: "verlaten", ru: "покидать" },
        { nl: "voorschrift", ru: "рецепт" },
        { nl: "geneesmiddel", ru: "лекарство" },
        { nl: "stempel", ru: "печать" },
        { nl: "handtekening", ru: "подпись" },
        { nl: "soeplepel", ru: "столовая ложка" },
        { nl: "kleine lepel", ru: "чайная ложечка" }
    ],
    "4 Feb": [
        { nl: "gewicht", ru: "вес" },
        { nl: "boeiend", ru: "очаровательный" },
        { nl: "verliezen", ru: "терять" },
        { nl: "valies", ru: "чемодан" },
        { nl: "fout", ru: "ошибка" },
        { nl: "briefje", ru: "купюра" },
        { nl: "bestellen", ru: "заказывать" },
        { nl: "echtgenote", ru: "супруга" },
        { nl: "echtgenoot", ru: "супруг" },
        { nl: "afdeling", ru: "департамент" },
        { nl: "meten", ru: "мерить" },
        { nl: "lengte", ru: "рост" },
        { nl: "gewicht", ru: "вес" },
        { nl: "wegen", ru: "взвешивать" }
    ],
    "8 Feb": [
        { nl: "zijn op zoek", ru: "находиться в поиске" },
        { nl: "ja hoor", ru: "послушай" },
        { nl: "iets, wat", ru: "немножечко" },
        { nl: "tot en met", ru: "до ... включительно" },
        { nl: "afdrogen", ru: "сушить" },
        { nl: "me", ru: "возвратная частица (ik)" },
        { nl: "je", ru: "возвратная частица (je)" },
        { nl: "zich", ru: "возвратная частица (u)" },
        { nl: "zich", ru: "возвратная частица (hij,ze)" },
        { nl: "ons", ru: "возвратная частица (we)" },
        { nl: "je", ru: "возвратная частица (jullie)" },
        { nl: "zich", ru: "возвратная частица (zij)" },
        { nl: "vergaderen", ru: "встречаться" },
        { nl: "verzamelen", ru: "собирать" },
        { nl: "pannenkoeken", ru: "блины" },
        { nl: "rooster", ru: "распорядок" },
        { nl: "lesrooster", ru: "расписание уроков" }
    ],
    "9 Feb": [
        { nl: "sterven", ru: "умирать" },
        { nl: "varen", ru: "плыть на корабле" },
        { nl: "belasting", ru: "налог" },
        { nl: "geleden", ru: "назад" },
        { nl: "onderzoeken", ru: "осматривать, исследовать" }
    ],
    "11 Feb": [
        { nl: "vorig", ru: "предыдущий" },
        { nl: "schat", ru: "милый, дорогой" },
        { nl: "slecht", ru: "плохо" },
        { nl: "slecht gezind", ru: "в расстоенных чувствах (bad mood)" },
        { nl: "haasten", ru: "торопить" },
        { nl: "haasten zich", ru: "торопиться" },
        { nl: "op het internet", ru: "в интернете" },
        { nl: "noorderlicht", ru: "севрное сияние" },
        { nl: "ijspegels", ru: "сосульки" },
        { nl: "dauw", ru: "роса" },
        { nl: "plas", ru: "лужа" },
        { nl: "glad ijs", ru: "гололед" },
        { nl: "sneeuwhoogte", ru: "сугроб" },
        { nl: "zonsopgang", ru: "рассвет" },
        { nl: "zonsondergang", ru: "закат" },
        { nl: "sneewvlok", ru: "снежинка" },
        { nl: "vries", ru: "иней, заморозки" },
        { nl: "tsunami", ru: "цунами" },
        { nl: "ijs", ru: "лед" },
        { nl: "storm", ru: "шторм" },
    ],
    "14 Feb": [
        { nl: "het hemd", ru: "рубашка" },
        { nl: "zakenreis", ru: "деловая поездка" },
        { nl: "zakenman", ru: "бизнесмен" },
        { nl: "toen", ru: "когда, в то время как" },
    ],
    "18 Feb": [
        { nl: "speelgoed", ru: "игрушка" },
        { nl: "duwen", ru: "толкать" },
        { nl: "stap", ru: "шаг" },
        { nl: "klaarmaken", ru: "подготовить" },
        { nl: "smakelijk", ru: "вкусный" },
        { nl: "gaatje", ru: "дырочка, яма" },
        { nl: "tips", ru: "советы" },
        { nl: "el", ru: "банка" },
        { nl: "ui", ru: "лук" },
        { nl: "takje", ru: "веточка" },
        { nl: "wortel", ru: "морковь" },
        { nl: "peper", ru: "перец" },
        { nl: "zout", ru: "соль" },
        { nl: "schillen", ru: "чистить" },
        { nl: "stuk", ru: "кусок" },
        { nl: "doen water in", ru: "наливать воду" },
        { nl: "toevoegen", ru: "добавлять" },
        { nl: "aan de kook brengen", ru: "доводить до кипения" },
        { nl: "mixen", ru: "мешать" },
        { nl: "kruiden", ru: "добавлять приправы" },
        { nl: "smaak", ru: "вкус" },
        { nl: "naar smaak", ru: "по вкусу" },
        { nl: "vormen", ru: " формировать" },
        { nl: "afsluiten", ru: "завершать" },
        { nl: "gewenste", ru: "желаемый" },
        { nl: "aantal", ru: "общее количество" },
        { nl: "binnen", ru: "в течение" },
        { nl: "balpen, pen", ru: "ручка" },
        { nl: "afgeven", ru: "сдавать" },
        { nl: "stam", ru: "корень" },
        { nl: "nicht", ru: "двоюродный брат" },
        { nl: "neef", ru: "двоюродная сестра" },
        { nl: "oom", ru: "дядя" },
        { nl: "kleinkind", ru: "внук" },
        { nl: "peuter", ru: "ребенок, до года" },
        { nl: "kleuter", ru: "ребенок, до 5 лет" },
        { nl: "crèche", ru: "ясли" },
        { nl: "kinderopvang", ru: "ясли" },
        { nl: "het kinderdagverblijf", ru: "прибывание в детском сад" },
        { nl: "kinderwagen", ru: "коляска" },
        { nl: "het huwelijk", ru: "брак" },
        { nl: "het echtpaar", ru: "супружеская пара" },
        { nl: "het stel", ru: "пара" },
        { nl: "liefde", ru: "любовь" },
        { nl: "groeien", ru: "расти" },
        { nl: "oppassen", ru: "остерегаться" },
        { nl: "kennen", ru: "знать" },
        { nl: "noemen, heten", ru: "называться" },
        { nl: "aardig", ru: "дружелюбный" },
        { nl: "gepensioneerd", ru: "на пенсии" },
        { nl: "roepnaam", ru: "кличка" },
        { nl: "ruzie", ru: "ссора" },
    ],
    "21 Feb": [
        { nl: "sap", ru: "сок" },
        { nl: "schilderij", ru: "картина" },
        { nl: "tevreden", ru: "довольный" },
        { nl: "lijken", ru: "казаться" },
        { nl: "je hebt gelijk", ru: "ты прав" },
        { nl: "vlak", ru: "сразу же" },
        { nl: "vertelen", ru: "рассказывать" },
        { nl: "betekenen", ru: "обозначать" },
        { nl: "tas", ru: "сумка" },
        { nl: "aandacht besteeden", ru: "уделять внимание" },
    ],
    "28 Feb": [
        { nl: "bijten", ru: "кусать" },
        { nl: "(hebben) gebeten", ru: "bijten -> VTT" },
        { nl: "beet / beten", ru: "bijten -> OVT" },
        { nl: "wekker aflopen", ru: "будильник прозвонит" },
        { nl: "koffer", ru: "чемодан" },
        { nl: "onder leiding", ru: "под руководством" },
        { nl: "vanaf", ru: "начиная с" },
        { nl: "verschillen", ru: "отличаться" },
        { nl: "pas", ru: "только" },
        { nl: "zowel ... als ...", ru: "и ... и ..." },
    ],
    "7 Mar (maken / doen)": [
        { nl: "de afwas doen", ru: "мыть посуду" },
        { nl: "het huishouden doen", ru: "заниматься домашними делами" },
        { nl: "het neit meer doen", ru: "ломаться" },
        { nl: "een afspraak maken", ru: "договариваться о встрече" },
        { nl: "blij maken", ru: "радовать" },
        { nl: "wakker maken", ru: "будить" },
        { nl: "lawaai maken", ru: "шуметь" },
        { nl: "ruzie maken", ru: "ссориться" },
        { nl: "een keus maken", ru: "делать выбор" },
        { nl: "in orde maken", ru: "приводить в порядок" },
        { nl: "kapotmaken", ru: "ломать" },
        { nl: "zorgen ervoor dat ...", ru: "делать так чтобы ..." },
        { nl: "doen alsof ...", ru: "делать вид будто ..." },
        { nl: "de/een conclusie trekken", ru: "делать вывод" },
        { nl: "zachter/harder zetten/doen", ru: "делать тише/шромче" },
        { nl: "Wat moet ik doen?", ru: "Что мне делать?" },
        { nl: "Er is niets aan te doen", ru: "Тут ничего не поделаешь" },
        { nl: "Ik doe mijn best!", ru: "Я стараюсь!" },
    ],
    "11 Mar": [
        { nl: "in het oosten", ru: "на востоке" },
        { nl: "bestan uit", ru: "состоять из (consists of)" },
        { nl: "zoveel mogelijk", ru: "как можно больше" },
        { nl: "vierkante", ru: "квадратный" },
        { nl: "regering", ru: "правительство" },
        { nl: "toren", ru: "башня" },
        { nl: "het gebied", ru: "площадь" },
    ],
    "14 Mar": [
        { nl: "kleding / kleren", ru: "одежда" },
        { nl: "rok", ru: "юбка" },
        { nl: "jurk / het kleedje", ru: "платье" },
        { nl: "het jasje", ru: "курточка" },
        { nl: "het overhemd", ru: "жилетка (официальная)" },
        { nl: "het pak", ru: "костюм" },
        { nl: "het vest", ru: "жилет" },
        { nl: "het colbert", ru: "пиджак" },
        { nl: "blouse", ru: "блузка" },
        { nl: "het T-shirt", ru: "майка" },
        { nl: "het ondergoed", ru: "белье" },
        { nl: "onderbroek", ru: "трусы" },
        { nl: "zwembroek", ru: "плавки" },
        { nl: "spijkerbroek", ru: "джинсы" },
        { nl: "zonnebril", ru: "солнечные очень" },
        { nl: "gymp", ru: "кеды" },
        { nl: "broekpak", ru: "комбенезон" },
        { nl: "het overall", ru: "рабочий комбенезон" },
        { nl: "slippers", ru: "сланцы" },
        { nl: "het hemd", ru: "рубашка" },
        { nl: "beha", ru: "бустгалтер" },
        { nl: "sok", ru: "носок" },
        { nl: "sokken", ru: "носки" },
        { nl: "kous", ru: "чулки" },
        { nl: "pantoffels", ru: "тапочки" },
        { nl: "laars", ru: "сапог" },
        { nl: "laarzen", ru: "сапоги" },
        { nl: "handschoenen", ru: "варешки" },
        { nl: "hoed", ru: "капюшон" },
        { nl: "pet", ru: "кепка" },
        { nl: "das", ru: "галстук" },
        { nl: "jas", ru: "куртка" },
        { nl: "regenjas", ru: "дождевик" },
        { nl: "portemonnee", ru: "кошелёк" },
        { nl: "koffer", ru: "чемодан" },
        { nl: "winkel", ru: "магазин" },
        { nl: "het warenhuis", ru: "торговый центр" },
        { nl: "markt", ru: "рынок" },
        { nl: "uitverkoop", ru: "распродажа" },
        { nl: "maat", ru: "размер" },
        { nl: "kwaliteit", ru: "качество" },
        { nl: "stof", ru: "ткань" },
        { nl: "het katoen", ru: "хлопок" },
        { nl: "het knoop", ru: "кнопка" },
        { nl: "shoppen", ru: "заниматься шоппингом" },
        { nl: "bestellen", ru: "заказывать" },
        { nl: "verkopen", ru: "продавать" },
        { nl: "terugsturen", ru: "возвращать" },
        { nl: "passen", ru: "подходить, мерить" },
        { nl: "ruilen", ru: "обменивать товар" },
        { nl: "drogen", ru: "cушить" },
        { nl: "smal", ru: "узкий" },
        { nl: "breed", ru: "широкий" },
        { nl: "strak", ru: "в обтяжку" },
        { nl: "wijd", ru: "широкий фасон" },
        { nl: "mouw", ru: "рукав" },
        { nl: "rits", ru: "молния" },
        { nl: "broekspijp", ru: "штанина" },
        { nl: "partronen", ru: "узоры" },
        { nl: "effen", ru: "однотонный" },

        { nl: "verdwijnen", ru: "исчезать" },
        { nl: "eruit ziet", ru: "выглядеть" },
        { nl: "kwijten", ru: "терять" },
        { nl: "verkorten", ru: "укорачивать" },
    ],
    "18 Mar": [
        { nl: "pompoen", ru: "тыква" },
        { nl: "graven", ru: "копать" },
        { nl: "aanraken", ru: "дотрагиваться" },
        { nl: "geweld", ru: "насилие" },
        { nl: "dezelfde / hetzelfde", ru: "тот же самый" },
    ],
    "21 Mar": [
        { nl: "leeuw", ru: "лев" },
        { nl: "konijn", ru: "кролик" },
        { nl: "haas", ru: "заяц" },
        { nl: "koe", ru: "корова" },
        { nl: "stier", ru: "бык" },
        { nl: "beer", ru: "медведь" },
        { nl: "het stinkdier", ru: "скунс" },
        { nl: "het hert", ru: "олень" },
        { nl: "olifant", ru: "слон" },
        { nl: "schildpad", ru: "черепаха" },
        { nl: "pony", ru: "пони" },
        { nl: "muis", ru: "мышь" },
        { nl: "gorilla", ru: "горилла" },
        { nl: "krokodil", ru: "крокодил" },
        { nl: "tijger", ru: "тигр" },
        { nl: "egel", ru: "ежик" },
        { nl: "ram", ru: "баран" },
        { nl: "paard", ru: "лошадь" },
        { nl: "schaap", ru: "овца" },
        { nl: "ezel", ru: "осел" },
        { nl: "wolf", ru: "волк" },
        { nl: "honingbij", ru: "пчела" },
        { nl: "het zwijn", ru: "кобан" },
        { nl: "aap", ru: "объезьяна" },
        { nl: "hamster", ru: "хомяк" },
        { nl: "geit", ru: "коза" },
        { nl: "kameel", ru: "верблюд" },
        { nl: "varken", ru: "свинья" },
        { nl: "neushoorn", ru: "носорог" },
    ],
    "25 Mar": [
        { nl: "voedsel", ru: "пища" },
        { nl: "verleden", ru: "прошлый" },
        { nl: "verloren", ru: "терять" },
    ],
    "28 Mar": [
        { nl: "geloven", ru: "верить" },
        { nl: "geloof", ru: "вера" },
        { nl: "proeven", ru: "пробовать, пытаться" },
        { nl: "duren", ru: "длиться, иметь продолжительность" },
        { nl: "landen", ru: "приземляться" },
        { nl: "gooien", ru: "выбрасывать" },
        { nl: "durven", ru: "осмелиться" },
        { nl: "ongeveer", ru: "примерно" },
        { nl: "helft, half, halve", ru: "половина" },
        { nl: "meesten", ru: "большинство" },
        { nl: "sommigen, sommige", ru: "некоторые" },
        { nl: "vaker", ru: "чаще" },
        { nl: "vieren", ru: "праздновать" },
        { nl: "opmerken", ru: "замечать" },
        { nl: "versieren", ru: "украшать" },
        { nl: "verhaal", ru: "рассказ" },
        { nl: "vuurwerk", ru: "салют" },
        { nl: "vasten", ru: "голодание, пост" },
        { nl: "volwassen", ru: "взрослый" },
    ],
    "1 Apr": [
        { nl: "verkeerde", ru: "неправильный, неположенный" },
        { nl: "juiste", ru: "правильный, положенный" },
        { nl: "verkeer", ru: "движение, трафик" },
        { nl: "verkeerslicht", ru: "светофор" },
        { nl: "opletten", ru: "обращать внимание" },
        { nl: "gewoonte", ru: "привычка" },
        { nl: "in verband met (i.v.m.)", ru: "в связи с" },
        { nl: "pistolets", ru: "булочки для бутербродов" },
        { nl: "charcuterie", ru: "нарезка" },
        { nl: "vis", ru: "рыба" },
        { nl: "zuiker", ru: "сахар" },
        { nl: "gerecht", ru: "блюдо" },
        { nl: "bijgerecht", ru: "гарнир" },
        { nl: "voorgerecht", ru: "закуска" },
        { nl: "nagerecht", ru: "десерт" },
        { nl: "ober", ru: "официант" },

        { nl: "als enige / de enige", ru: "единственный" },
        { nl: "delen", ru: "делить (share)" },
        { nl: "hoe dan ook", ru: "в любом случае" },
        { nl: "vernederd", ru: "униженный" },
        { nl: "vernederen", ru: "унизить" },
        { nl: "gelukt", ru: "успех" },
        { nl: "bladzijde", ru: "страница" },
        { nl: "dichterbij", ru: "ближе" },
        { nl: "plagen", ru: "дразнить" },
        { nl: "zoals gewoonlijk", ru: "как обычно, по-прежнему" },
        { nl: "godzijdank", ru: "слава богу" },
        { nl: "beseffen", ru: "осознавать (realize)" },
        { nl: "voorspelbaar", ru: "предсказуемый" },
        { nl: "geheim", ru: "секрeтный" },
        { nl: "bericht, boodschap", ru: "послание" },
        { nl: "wezen", ru: "быть" },
        { nl: "dom", ru: "глупый" },
        { nl: "bodem", ru: "дно" },
        { nl: "slingeren", ru: "качаться" },
        { nl: "doorgaan", ru: "продолжать" },
        { nl: "kans", ru: "шанс, возможность" },
        { nl: "zwak", ru: "слабый" },
        { nl: "taai", ru: "жесткий" },
        { nl: "hou op", ru: "стой" },
        { nl: "koesteren", ru: "ценить" },
        { nl: "kietelen", ru: "щекотать" },
        { nl: "rommeltje", ru: "беспорядок, бардак" },
        { nl: "steen", ru: "камень" },
        { nl: "gooien", ru: "кидать" },
        { nl: "uitdagen", ru: "соревноваться (to challenge)" },
        { nl: "bedoelen", ru: "иметь в виду (mean)" },
        { nl: "verslaan", ru: "побеждать (defeat)" },
        { nl: "vasthouden", ru: "взять (hold)" },
        { nl: "gelijkspel", ru: "ничья" },
        { nl: "afleiden", ru: "отвлекать" },
        { nl: "weer", ru: "снова" },
        { nl: "triest", ru: "печальный" },
        { nl: "schuld", ru: "вина" },
    ],
    "4 Apr": [
        { nl: "verdienen", ru: "зарабатывать" },
        { nl: "redelijk", ru: "разумно" },
        { nl: "schijnen", ru: "казаться" },
        { nl: "binnenkort", ru: "скорое время" },
        { nl: "enkele", ru: "парочка, несколько" },
        { nl: "toekomst", ru: "будущее" },
        { nl: "baan", ru: "рабйота" },
    ],
    "7 Apr": [
        { nl: "spontaan", ru: "спонтанный" },
        { nl: "lichaamsbouw", ru: "телосложение" },
        { nl: "knap", ru: "привлекательный" },
        { nl: "vorm", ru: "форма" },
        { nl: "vrojlijk", ru: "жизнерадостный" },
        { nl: "overzicht", ru: "обзор" },
        { nl: "stoppelbaard", ru: "щетина борода" },
        { nl: "bottines", ru: "сапоги" },
        { nl: "veters", ru: "шнурки" },
        { nl: "donkerblond", ru: "темно-русый" },
        { nl: "borstzakje", ru: "нагрудный карман" },
        { nl: "rood haar", ru: "рыжие волосы" },
        { nl: "snor", ru: "усы" },
        { nl: "platte schoenen", ru: "обувь на плоской подошве" },
        { nl: "krullend haar", ru: "кудрявые волосы" },
        { nl: "tapijt", ru: "ковер" },
        { nl: "stinken", ru: "вонять" },
        { nl: "scheef", ru: "кривой" },
        { nl: "prachtig", ru: "красивый" },
        { nl: "onderweg", ru: "по пути" },
        { nl: "jager", ru: "охотник" },
    ],
    "11 Apr": [
        { nl: "nogal", ru: "довольно" },
        { nl: "geschiedenis", ru: "история (как наука)" },
        { nl: "kennis", ru: "знание" },
        { nl: "verleden", ru: "прошлое" },
        { nl: "aarde", ru: "земля" },
        { nl: "bekende / beroemde", ru: "известный" },
        { nl: "dergelijke", ru: "прочее" },
        { nl: "wet", ru: "закон" },
        { nl: "eerder", ru: "ранее" },
        { nl: "beveiligen", ru: "обезопасить (to secure)" },
        { nl: "met de deur in huis vallen", ru: "переходить прямо к делу" },
        { nl: "alsof er een engeltje over je tong piest", ru: "очень вкусная еда" },
        { nl: "nu komt de aap uit de mouw", ru: "правда открывается" },
        { nl: "met zijn neus in de boter vallen", ru: "оказаться в правильном месте в правильное время" },
        { nl: "ben je van de trap gevallen", ru: "странная прическа" },
        { nl: "daar kan ik geen chocola van maken", ru: "не понимаю о чем речь" },
        { nl: "wat heb ik nou aan mijn fiets hangen?", ru: "что мне делать дальше?" },
        { nl: "we zullen dat varkentje wel even wassen", ru: "мы доведем дело до завершения" },
        { nl: "praten over koetjes en kalfjes", ru: "говорить о чем-то не важном (smalltalk)" },
        { nl: "nu breekt mijn klomp", ru: "случилось что-то непредвиденное" },
    ],
    "14 Apr": [
        { nl: "verpakking", ru: "упаковка" },
        { nl: "ordenen", ru: "упорядочивать" },
        { nl: "blik", ru: "металическая банка" },
        { nl: "fles", ru: "бутылка" },
        { nl: "pot", ru: "стеклянная банка" },
        { nl: "tros", ru: "связка, пучок" },
        { nl: "het gehakt", ru: "фарш" },
        { nl: "ajuin, ui", ru: "луч" },
        { nl: "look", ru: "чеснок" },
        { nl: "room", ru: "сливки" },
        { nl: "het roomijs", ru: "cливочное масло" },
        { nl: "tandenborstel", ru: "зубная щетка" },
        { nl: "diepvries", ru: "отдел заморозки" },
        { nl: "beenhouwerij", ru: "мясной отдел" },
        { nl: "zuivel", ru: "молочные продукты" },
        { nl: "voeding", ru: "продукты питания" },
        { nl: "druiven", ru: "виноград" },
        { nl: "wasmiddel", ru: "стиральные порошок" },
        { nl: "mosselen", ru: "мидии" },
        { nl: "punkzakje", ru: "кулёк бумаги" },
        { nl: "stoofkarbonades", ru: "тушенка с мясом" },
        { nl: "asperges", ru: "спаржа" },
        { nl: "peterselie", ru: "петрушка" },
        { nl: "scampi's", ru: "креветки" },
        { nl: "slagroom", ru: "взбитые сливки" },
        { nl: "hoorntje", ru: "рожок" },
        { nl: "bolletjes ", ru: "шарик" },
        { nl: "plat", ru: "блюдо" },
        { nl: "gebak", ru: "выпечка" },
        { nl: "wat mag het zijn?", ru: "что это такое?" },
        { nl: "pinnen", ru: "платить картой" },
    ],
    "19 Apr": [
        { nl: "bureau", ru: "письменный стол (desk)" },
        { nl: "wijzen", ru: "показывать" },
        { nl: "verontschuldiging", ru: "извинения" },
        { nl: "raegeren", ru: "реагировать" },
        { nl: "rechtdoor", ru: "прямо" },
        { nl: "tot aan", ru: "вплоть до" },
        { nl: "het zebrapad", ru: "пешеходный переход" },
        { nl: "stoplicht", ru: "светофор" },
        { nl: "rechtsaf", ru: "повернить направо" },
        { nl: "het kruispunt", ru: "перекресток" },
        { nl: "rotonde", ru: "кольцевое движение" },
        { nl: "afslag", ru: "выезд" },
        { nl: "onwerpen", ru: "проектировать" },
        { nl: "tentoonstelling", ru: "выставка" },
        { nl: "bezienswaardigheid", ru: "достопримечательность" },
        { nl: "uitroepen", ru: "называть" },
        { nl: "uitzicht", ru: "вид" },
    ],
    "OVT:1": [
        { nl: "deed aan / deden aan", ru: "aandoen -> OVT" },
        { nl: "kwam aan / kwamen aan", ru: "aankomen -> OVT" },
        { nl: "waste af / wasten af", ru: "afwassen -> OVT" },
        { nl: "bakte / bakten", ru: "bakken -> OVT" },
        { nl: "begon / begonnen", ru: "beginnen -> OVT" },
        { nl: "bezocht / bezochten", ru: "bezoeken -> OVT" },
        { nl: "bleef / bleven", ru: "blijven -> OVT" },
        { nl: "brak / braken", ru: "breken -> OVT" },
        { nl: "bracht / brachten", ru: "brengen -> OVT" },
        { nl: "dacht / dachten", ru: "denken -> OVT" },
    ],
    "VTT:1": [
        { nl: "(hebben) aangedaan", ru: "aandoen -> VTT" },
        { nl: "(zijn) aangekomen", ru: "aankomen -> VTT" },
        { nl: "(hebben) afgewassen", ru: "afwassen -> VTT" },
        { nl: "(hebben) gebakken", ru: "bakken -> VTT" },
        { nl: "(zijn) begonnen", ru: "beginnen -> VTT" },
        { nl: "(hebben) bezocht", ru: "bezoeken -> VTT" },
        { nl: "(zijn) gebleven", ru: "blijven -> VTT" },
        { nl: "(hebben) gebroken", ru: "breken -> VTT" },
        { nl: "(hebben) gebracht", ru: "brengen -> VTT" },
        { nl: "(hebben) gedacht", ru: "denken -> VTT" },
    ],
    "OVT:2": [
        { nl: "deed / deden", ru: "doen -> OVT" },
        { nl: "droeg / droegen", ru: "dragen -> OVT" },
        { nl: "dronk / dronken", ru: "drinken -> OVT" },
        { nl: "at / aten", ru: "eten -> OVT" },
        { nl: "ging / gingen", ru: "gaan -> OVT" },
        { nl: "gaf / gaven", ru: "geven -> OVT" },
        { nl: "hing / hingen", ru: "hangen -> OVT" },
        { nl: "had / hadden", ru: "hebben -> OVT" },
        { nl: "hielp / hielpen", ru: "helpen -> OVT" },
        { nl: "nam in / namen in", ru: "innemen -> OVT" },
    ],
    "VTT:2": [
        { nl: "(hebben) gedaan", ru: "doen -> VTT" },
        { nl: "(hebben) gedragen", ru: "dragen -> VTT" },
        { nl: "(hebben) gedronken", ru: "drinken -> VTT" },
        { nl: "(hebben) gegeten", ru: "eten -> VTT" },
        { nl: "(zijn) gegaan", ru: "gaan -> VTT" },
        { nl: "(hebben) gegeven", ru: "geven -> VTT" },
        { nl: "(hebben) gehangen", ru: "hangen -> VTT" },
        { nl: "(hebben) gehad", ru: "hebben -> VTT" },
        { nl: "(hebben) geholpen", ru: "helpen -> VTT" },
        { nl: "(hebben) ingenomen", ru: "innemen -> VTT" },
    ],
    "OVT:3": [
        { nl: "koos / kozen", ru: "kiezen -> OVT" },
        { nl: "keek / keken", ru: "kijken -> OVT" },
        { nl: "kwam / kwamen", ru: "komen -> OVT" },
        { nl: "kocht / kochten", ru: "kopen -> OVT" },
        { nl: "kreeg / kregen", ru: "krijgen -> OVT" },
        { nl: "kon / konden", ru: "kunnen -> OVT" },
        { nl: "lachte / lachten", ru: "lachen -> OVT" },
        { nl: "las / lazen", ru: "lezen -> OVT" },
        { nl: "lag / lagen", ru: "liggen -> OVT" },
        { nl: "liep / liepen", ru: "lopen -> OVT" },
    ],
    "VTT:3": [
        { nl: "(hebben) gekozen", ru: "kiezen -> VTT" },
        { nl: "(hebben) gekeken", ru: "kijken -> VTT" },
        { nl: "(zijn) gekomen", ru: "komen -> VTT" },
        { nl: "(hebben) gekocht", ru: "kopen -> VTT" },
        { nl: "(hebben) gekregen", ru: "krijgen -> VTT" },
        { nl: "(hebben) gekund", ru: "kunnen -> VTT" },
        { nl: "(hebben) gelachen", ru: "lachen -> VTT" },
        { nl: "(hebben) gelezen", ru: "lezen -> VTT" },
        { nl: "(hebben) gelegen", ru: "liggen -> VTT" },
        { nl: "(hebben/zijn) gelopen", ru: "lopen -> VTT" },
    ],
    "OVT:NNN": [
        { nl: "xxx", ru: "1111 -> OVT" },
        { nl: "xxx", ru: "2222 -> OVT" },
        { nl: "xxx", ru: "3333 -> OVT" },
        { nl: "xxx", ru: "4444 -> OVT" },
        { nl: "xxx", ru: "5555 -> OVT" },
        { nl: "xxx", ru: "6666 -> OVT" },
        { nl: "xxx", ru: "7777 -> OVT" },
        { nl: "xxx", ru: "8888 -> OVT" },
        { nl: "xxx", ru: "9999 -> OVT" },
        { nl: "xxx", ru: "0000 -> OVT" },
    ],
    "VTT:NNN": [
        { nl: "(hebben) xxx", ru: "1111 -> VTT" },
        { nl: "(hebben) xxx", ru: "2222 -> VTT" },
        { nl: "(hebben) xxx", ru: "3333 -> VTT" },
        { nl: "(hebben) xxx", ru: "4444 -> VTT" },
        { nl: "(hebben) xxx", ru: "5555 -> VTT" },
        { nl: "(hebben) xxx", ru: "6666 -> VTT" },
        { nl: "(hebben) xxx", ru: "7777 -> VTT" },
        { nl: "(hebben) xxx", ru: "8888 -> VTT" },
        { nl: "(hebben) xxx", ru: "9999 -> VTT" },
        { nl: "(hebben) xxx", ru: "0000 -> VTT" },
    ],
    "meer OVT+VTT": [
        { nl: "(zijn) geweest", ru: "zijn -> VTT" },
        { nl: "was / waren", ru: "zijn -> OVT" },
        { nl: "(hebben) gezocht", ru: "zoeken -> VTT" },
        { nl: "(hebben) ontbeten", ru: "ontbijten -> VTT" },
        { nl: "(hebben) gemoeten", ru: "moeten -> VTT" },
        { nl: "zocht / zochten", ru: "zoeken -> OVT" },
        { nl: "ontbeet / ontbeten", ru: "ontbijten -> OVT" },
        { nl: "nam / namen", ru: "nemen -> OVT" },
        { nl: "moest / moesten", ru: "moeten -> OVT" },
    ],
};

class Card {
    constructor() {
        this.state = 'init';
        this.node = document.getElementById("card");
        this.node.onclick = () => this.onAnswer();
        document.getElementById("btn-y").onclick = () => this.onRight();
        document.getElementById("btn-n").onclick = () => this.onWrong();
    }

    reset(q, a, onDone) {
        this.question = q;
        this.answer = a;
        this.onDone = onDone;
        this.state = 'question';

        this.node.innerText = this.question;
        document.getElementById("answer").style.display = "none";
    }

    onAnswer() {
        if (this.state !== 'question') {
            return;
        }
        this.state = 'answer';
        this.node.innerText = this.answer;
        document.getElementById("answer").style.display = "flex";
    }

    onRight() {
        if (this.state !== 'answer') {
            return;
        }
        this.state = 'done';
        this.onDone(true);
    }

    onWrong() {
        if (this.state !== 'answer') {
            return;
        }
        this.state = 'done';
        this.onDone(false);
    }
}

function shuffled(arr) {
    let res = [];
    for (let e of arr) {
        res.push(e);
    }
    for (let i = 0; i < res.length - 1; i++) {
        let j = i + Math.floor(Math.random() * (res.length - i));
        if (j != i) {
            let tmp = res[i];
            res[i] = res[j]
            res[j] = tmp;
        }
    }
    return res;
}

class Exercise {
    constructor(card, words, question_key, answer_key) {
        this.card = card;
        this.words = words;
        this.deck = shuffled([...Array(this.words.length).keys()])
        this.question_key = question_key;
        this.answer_key = answer_key;
        this.id = -1;
        for (let word of this.words) {
            word.total = 0;
            word.right = 0;
            word.maCorrect = 0.5; // correctness moving average
        };
    }

    getWeight(w) {
        return 1 - w.maCorrect;
    }

    isEligible(id, w) {
        if (id == this.id) {
            return false;
        }
        if (w.maCorrect > 0.90) {
            return false;
        }
        return true;
    }

    select_random() {
        let weights = [];
        let totalWeight = 0;
        for (let i = 0; i < this.words.length; i++) {
            if (!this.isEligible(i, this.words[i])) {
                continue;
            }
            totalWeight += this.getWeight(this.words[i]);
        }
        if (totalWeight == 0) {
            return -1;
        }
        let p = Math.random() * totalWeight;
        let w = 0;
        for (let i = 0; i < this.words.length; i++) {
            if (!this.isEligible(i, this.words[i])) {
                continue;
            }
            w += this.getWeight(this.words[i]);
            if (p < w) {
                return i;
            }
        }
        console.log("Error generating random word id in Exercise.select()");
        return this.words.length - 1;
    }

    select_from_deck() {
        if (this.deck.length > 0) {
            return this.deck.shift();
        } else {
            return -1;
        }
    }

    select() {
        //return this.select_random();
        return this.select_from_deck();
    }

    run() {
        this.id = this.select();
        if (this.id == -1) {
            this.congratulate();
            return;
        }
        this.word = this.words[this.id];
        this.card.reset(this.word[this.question_key], this.word[this.answer_key], (isCorrect) => this.gatherResult(isCorrect));
    }

    congratulate() {
        document.getElementById("card").innerText = "Je hebt deze woorden geleerd!";
        document.getElementById("answer").style.display = "none";
    }

    gatherResult(isCorrect) {
        this.word.total++;
        if (isCorrect) {
            this.word.right++;
        } else {
            this.deck.push(this.id); // add word under the deck to ask again later
        }
        let maCoef = 0.5;
        this.word.maCorrect = maCoef * this.word.maCorrect + (1 - maCoef) * (isCorrect ? 1 : 0);
        this.run();
    }
}

class DictList {
    constructor() {
        this.card = new Card();
        this.selected = [];
    }

    render() {
        let dicts = document.getElementById("dicts");
        let html = '<p>kies woordenboeken:</p>';
        for (let name in DICTS) {
            html += `<div id="dict-${name}" class="dicts-item">${name}</div>`;
        }
        dicts.innerHTML = html;
        for (let name in DICTS) {
            document.getElementById(`dict-${name}`).onclick = () => this.onToggle(name);
        }
        document.getElementById("btn-ru-nl").onclick = () => this.onRun("ru", "nl");
        document.getElementById("btn-nl-ru").onclick = () => this.onRun("nl", "ru");
    }

    onToggle(name) {
        let node = document.getElementById(`dict-${name}`);
        let idx = this.selected.indexOf(name);
        if (idx == -1) {
            this.selected.push(name);
            node.classList.add("dicts-item-selected");
        } else {
            this.selected.splice(idx, 1);
            node.classList.remove("dicts-item-selected");
        }
    }

    onRun(question_key, answer_key) {
        let words = [];
        for (let name of this.selected) {
            for (let word of DICTS[name]) {
                words.push(word);
            }
        }
        if (words.length > 0) {
            document.getElementById("card").style.display = "";
            document.getElementById("dicts").style.display = "none";
            document.getElementById("dicts-menu").style.display = "none";
            let excecise = new Exercise(this.card, words, question_key, answer_key);
            excecise.run();
        }
    }
}
